{ pkgs, ... }:
{
  programs.tmux = {
    enable = true;
    aggressiveResize = true;
    baseIndex = 1;
    clock24 = true;
    customPaneNavigationAndResize = true;
    escapeTime = 0;
    focusEvents = true;
    historyLimit = 200000;
    keyMode = "vi";
    mouse = true;
    prefix = "C-a";
    resizeAmount = 3;
    sensibleOnTop = true;
    terminal = "tmux-256color";

    plugins = with pkgs.tmuxPlugins; [
      yank
      cpu
      tmux-fzf
      tmux-thumbs
      {
        plugin = resurrect;
        extraConfig = ''
          set -g @resurrect-capture-pane-contents 'on'
          set -g @resurrect-processes 'ssh mosh hx nvim vim lazygit btop'
          set -g @resurrect-save-shell-history 'on'
        '';
      }
      {
        plugin = continuum;
        extraConfig = ''
          set -g @continuum-restore 'on'
          set -g @continuum-save-interval '10'
        '';
      }
    ];

    extraConfig = ''
      # Modern terminal features and reliable remote clipboard support.
      set -as terminal-features ',xterm*:RGB:clipboard:hyperlinks:usstyle'
      set -as terminal-features ',ghostty:RGB:clipboard:hyperlinks:usstyle'
      set -g set-clipboard on
      set -g @thumbs-osc52 1
      set -g extended-keys on
      set -g extended-keys-format csi-u
      set -g focus-events on

      # Keep the workspace predictable over SSH, Mosh, and Moonlight.
      set -g detach-on-destroy off
      set -g renumber-windows on
      set -g repeat-time 600
      set -g display-time 1500
      set -g status-interval 2
      set -g status-position bottom
      set -g automatic-rename on
      set -g automatic-rename-format '#{pane_current_command}'
      set -g update-environment 'DISPLAY WAYLAND_DISPLAY SSH_AUTH_SOCK SSH_CONNECTION'

      # Splits and windows inherit the active pane's directory.
      bind -N 'New window here' c new-window -c '#{pane_current_path}'
      bind -N 'Split right' | split-window -h -c '#{pane_current_path}'
      bind -N 'Split below' - split-window -v -c '#{pane_current_path}'
      bind -N 'Swap with previous window' < swap-window -t -1
      bind -N 'Swap with next window' > swap-window -t +1

      # Pop-up tools: no layout disruption, instant dismissal with Escape.
      bind -N 'Lazygit popup' g display-popup -E -w 92% -h 92% -d '#{pane_current_path}' 'lazygit'
      bind -N 'Helix popup' e display-popup -E -w 92% -h 92% -d '#{pane_current_path}' 'hx .'
      bind -N 'System monitor popup' b display-popup -E -w 88% -h 88% 'btop'
      bind -N 'Session and window tree' s choose-tree -Zw

      # Quality-of-life controls.
      bind -N 'Reload tmux configuration' r source-file ~/.config/tmux/tmux.conf \; display-message ' tmux reloaded '
      bind -N 'Toggle pane synchronization' C-s setw synchronize-panes \; display-message ' pane sync: #{?pane_synchronized,on,off} '
      bind -N 'Show key bindings' ? list-keys -N
      bind -N 'Clear pane and history' C-l send-keys C-l \; clear-history

      # Vim-style copy mode. tmux-yank and OSC 52 handle local and remote copies.
      bind -T copy-mode-vi v send-keys -X begin-selection
      bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
      bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

      # Generated by Noctalia from the current wallpaper palette.
      source-file -q ~/.config/tmux/noctalia.conf
    '';
  };
}
