{ ... }:
{
  xdg.configFile."zed/settings.json" = {
    force = true;
    text = ''
      // Zed settings
      //
      // Theme colors are generated by Noctalia's matugen template at
      // ~/.config/zed/themes/noctalia.json.
      {
        "which_key": {
          "delay_ms": 500,
          "enabled": true
        },
        "helix_mode": true,
        "telemetry": {
          "diagnostics": false,
          "metrics": false
        },
        "base_keymap": "Cursor",
        "ui_font_size": 16,
        "buffer_font_size": 15,
        "theme": {
          "mode": "system",
          "light": "Noctalia Light",
          "dark": "Noctalia Dark"
        }
      }
    '';
  };
}
