{ lib, pkgs, ... }:
let
  settings = ''
    // Zed settings
    //
    // Theme colors are generated by Noctalia's matugen template at
    // ~/.config/zed/themes/noctalia.json.
    {
      "which_key": {
        "delay_ms": 500,
        "enabled": true
      },
      "helix_mode": true,
      "telemetry": {
        "diagnostics": false,
        "metrics": false
      },
      "base_keymap": "Cursor",
      "ui_font_size": 16,
      "buffer_font_size": 15,
      "theme": {
        "mode": "system",
        "light": "Noctalia Light",
        "dark": "Noctalia Dark"
      }
    }
  '';
  settingsFile = pkgs.writeText "zed-settings.json" settings;
in
{
  # Keep this as a real file, not a Nix store symlink, so Noctalia can touch it
  # after regenerating the Zed theme and prompt Zed to reload the theme data.
  home.activation.zedSettings = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    run mkdir -p "$HOME/.config/zed"
    run rm -f "$HOME/.config/zed/settings.json"
    run install -m 0644 "${settingsFile}" "$HOME/.config/zed/settings.json"
  '';
}
