{username, ...}: {
  programs.ghostty = {
    enable = true;
    enableBashIntegration = false;
    enableZshIntegration = true;
    settings = {
      font-family = "Space Mono";
      font-size = 14;
      font-thicken = false;
      font-feature = ["ss04" "ss01"];
      bold-is-bright = false;
      adjust-box-thickness = 1;
      cursor-style = "bar";
      cursor-style-blink = false;
      copy-on-select = false;
      confirm-close-surface = false;
      adjust-cursor-thickness = 1;
      mouse-hide-while-typing = true;
      window-padding-x = 4;
      window-padding-y = 6;
      window-padding-balance = true;
      title = "GhosTTY";
      gtk-single-instance = true;
      app-notifications = ["no-clipboard-copy"];
      config-file = "/home/${username}/.config/ghostty/config-dankcolors";
      # Note: config-dankcolors is generated by matugen
      # Ghostty will automatically load it from ~/.config/ghostty/config-dankcolors
      # when it exists. We don't set config-file here to avoid home-manager
      # validation errors during build time.
    };
  };
}
